version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
